# This is the SAM template that represents the architecture of your serverless application
# https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/serverless-sam-template-basics.html

# The AWSTemplateFormatVersion identifies the capabilities of the template
# https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/format-version-structure.html
AWSTemplateFormatVersion: 2010-09-09
Description: >-
  homepage-ricky-ses

# Transform section specifies one or more macros that AWS CloudFormation uses to process your template
# https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/transform-section-structure.html
Transform:
  - AWS::Serverless-2016-10-31
Parameters:
  FromEmail:
    Type: String
    Default: 'your@email.com'
    Description: (Required) Represents the email sender. Must be a SES verified email. If you attempt to send email using a non-verified address or domain, the operation results in an "Email address not verified" error. Minimum 4 characters.
    ConstraintDescription: 'Required. Must be a SES verified email address.'
  ToEmail:
    Type: String
    Default: 'your@email.com'
    Description: (Required) Represents the email to send to. If you're in the sandbox environment, must be a SES verified email. .
    ConstraintDescription: 'Required. Must be a valid SES email address.'
  CorsOrigin:
    Type: String
    Default: ''
    Description: (Optional) Cross-origin resource sharing (CORS) Origin. You can specify a single origin, all "*" or leave empty and no CORS will be applied.
    MaxLength: 250
# Resources declares the AWS resources that you want to include in the stack
# https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/resources-section-structure.html
Resources:
  # Each Lambda function is defined by properties:
  # https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction

  # This is a Lambda function config associated with the source code: get-all-items.js
  sendEmailFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: src/send-email.handler
      Runtime: nodejs16.x
      Architectures:
        - x86_64
      MemorySize: 128
      Timeout: 100
      Description: Serverless function to expose limited SES functionality for use on the contact form of my personal homepage
      Policies:
        - SESCrudPolicy:
            IdentityName: !Ref FromEmail
      Environment:
        Variables:
          FROM_EMAIL: !Ref FromEmail
          TO_EMAIL: !Ref ToEmail
          CORS_ORIGIN: !Ref CorsOrigin
      Events:
        EmailApi:
          Type: Api
          Properties:
            Path: /send
            Method: POST
        EmailOptionsApi:
          Type: Api
          Properties:
            Path: /send
            Method: OPTIONS
  # Each Lambda function is defined by properties:
  # https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction

  # This is a Lambda function config associated with the source code: get-by-id.js

  # DynamoDB table to store item: {id: &lt;ID&gt;, name: &lt;NAME&gt;}


Outputs:
  WebEndpoint:
    Description: "API Gateway endpoint URL for Prod stage"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/send"
